//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bidly.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_role
    {
        public int Member_role_id { get; set; }
        public Nullable<int> Member_id { get; set; }
        public Nullable<int> Role_id { get; set; }
    }
}
