//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bidly.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbonline_ShoppingEntities : DbContext
    {
        public dbonline_ShoppingEntities()
            : base("name=dbonline_ShoppingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Member_role> Member_role { get; set; }
        public virtual DbSet<Shipping_details> Shipping_details { get; set; }
        public virtual DbSet<Tbl_cart> Tbl_cart { get; set; }
        public virtual DbSet<Tbl_cartstatus> Tbl_cartstatus { get; set; }
        public virtual DbSet<Tbl_category> Tbl_category { get; set; }
        public virtual DbSet<Tbl_member> Tbl_member { get; set; }
        public virtual DbSet<Tbl_roles> Tbl_roles { get; set; }
        public virtual DbSet<Tbl_slideImage> Tbl_slideImage { get; set; }
        public virtual DbSet<Tbl_product> Tbl_product { get; set; }
    }
}
