//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bidly.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipping_details
    {
        public int Shipping_details_id { get; set; }
        public Nullable<int> Member_id { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Zip_code { get; set; }
        public Nullable<int> Order_id { get; set; }
        public Nullable<decimal> Amount_paid { get; set; }
        public string Payment_type { get; set; }
    
        public virtual Tbl_member Tbl_member { get; set; }
    }
}
