//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bidly.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_cartstatus
    {
        public int cart_StatusId { get; set; }
        public string cart_Status { get; set; }
    }
}
