//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bidly.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_category()
        {
            this.Tbl_product = new HashSet<Tbl_product>();
        }
    
        public int Category_Id { get; set; }
        public string Category_Name { get; set; }
        public Nullable<bool> Is_active { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_product> Tbl_product { get; set; }
    }
}
