//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bidly.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_member()
        {
            this.Shipping_details = new HashSet<Shipping_details>();
        }
    
        public int Member_id { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Email_id { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Is_active { get; set; }
        public Nullable<bool> Is_delete { get; set; }
        public Nullable<System.DateTime> Created_on { get; set; }
        public Nullable<System.DateTime> Modified_on { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shipping_details> Shipping_details { get; set; }
    }
}
