//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bidly.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_cart
    {
        public int cart_id { get; set; }
        public Nullable<int> Product_id { get; set; }
        public Nullable<int> member_id { get; set; }
        public Nullable<int> CartStatus_id { get; set; }
    
        public virtual Tbl_product Tbl_product { get; set; }
    }
}
