//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bidly.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_product()
        {
            this.Tbl_cart = new HashSet<Tbl_cart>();
        }
    
        public int Product_Id { get; set; }
        public string Product_Name { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<bool> Is_active { get; set; }
        public Nullable<bool> Is_delete { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
        public string Description { get; set; }
        public string Product_image { get; set; }
        public Nullable<bool> Is_featured { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_cart> Tbl_cart { get; set; }
        public virtual Tbl_category Tbl_category { get; set; }
    }
}
